/** 交融品牌常量（宿主只引用，勿在开源路径散落硬编码） */

export const APP_NAME = 'JiaorongAI'

export const APP_DOCUMENT_TITLE = APP_NAME

export const HTTP_X_TITLE = APP_NAME

export function buildAppUserAgent(version: string): string {
  return `${APP_NAME}/${version}`
}

export const WATERMARK_BRAND = APP_NAME

export const WATERMARK_TIP = `Generated by ${APP_NAME}`

export const ARTIFACTS_FOOTER = `Generated with ${APP_NAME} | All page content is AI-generated and for reference only`
