#!/usr/bin/env node
/**
 * 每次打包前生成随机 DEFAULT_SKILLS_SEED_BUILD_ID，
 * 使同版本覆盖安装也会触发默认技能补缺。
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { randomBytes } from 'node:crypto'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outFile = join(__dirname, '../lib/defaultSkillsSeedBuildId.generated.ts')

const buildId = `${Date.now().toString(36)}-${randomBytes(4).toString('hex')}`

const contents = `/** AUTO-GENERATED by generateDefaultSkillsSeedBuildId.mjs — do not edit. */
export const DEFAULT_SKILLS_SEED_BUILD_ID = '${buildId}'
`

writeFileSync(outFile, contents, 'utf8')
console.info(`[jiaorong] default skills seed build id → ${buildId}`)
