export const INITIAL_MESSAGE_RESTORE_COUNT = 10
export const OLDER_MESSAGE_PAGE_SIZE = 20
export const TOP_HISTORY_PREFETCH_PX = 300
export const INITIAL_SESSION_PAGE_SIZE = 10
export const OLDER_SESSION_PAGE_SIZE = 20
export const SESSION_LIST_LOAD_MORE_PX = 80
